Support for legacyfabric
mindstorm38/portablemc pull request #197
Opened 2024-02-23 21:18 UTC by BluCobalt

@Legacy-Fabric ports the fabric toolchain to versions pre 1.14. This pr just adds legacyfabric's meta, using it for versions 1.3.2-1.13.2.

2024-02-23 21:52 UTC, mindstorm38 requested changes
Thank you so much! I didn't know that it existed until now. I have some changes that in my opinion would better fit the stability philosophy of the launcher...

First, I think that this API shouldn't silently hide the normal fabric one (just like we've done with NeoForge), in my opinion we should've a specific function like `_with_legacyfabric`. Notice the leading underscore, because I would also prefer if these API symbols are unstable -for some time-, to avoid breaking API later if we change the design around legacy fabric support!

This implies that you should also make changes to the CLI (which is allowed to use unstable API because it's internal). Basically adding a search case (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/__init__.py#L276) and a start handler (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/__init__.py#L448). But also a command line argument to change the version prefix (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/parse.py#L51, https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/parse.py#L147), add it for autocompletion (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/parse.py#L162) and add it to search kinds (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/parse.py#L216). And ***finally*** just add a lang much like for Fabric and Quilt (https://github.com/mindstorm38/portablemc/blob/main/portablemc/cli/lang.py).

Sorry if it feels like a lot more complicated, but I think that it should be quite fast to actually implement, and it allows us to avoid hardcoding supported versions much like you've done wiht `LEGACYFABRIC_VERSIONS`, which would be complicated to maintain.

Thank you again!

2024-02-23 21:54 UTC, mindstorm38 commented
Also, could you retarget your pull request to the `v4.3` branch?

2024-03-02 12:41 UTC, mindstorm38 commented
Any update on your side? If you need help, do not hesitate, I can just merge this one on the v4.3 branch and do the work myself.

2024-03-15 14:57 UTC, mindstorm38 commented
If you don't answer by tomorrow I'll merge your work and do the modifications myself.

2024-03-15 15:40 UTC, BluCobalt commented
Sorry, I got completely caught up in school and forgot about this. I'd be happy to work on it today.

2024-03-15 16:24 UTC, mindstorm38 commented
No hurry tho, I thought you really forgot this pr, and I was going to modify it, keeping your work of course.

2024-03-15 20:59 UTC, BluCobalt commented
Should I add lang for everything loader specific, or just for `legacyfabric_prefix` for the help text in `parse.py`?

2024-03-15 21:07 UTC, BluCobalt commented
See #205

2024-03-15 21:07 UTC, closed without merging