Add basic optifine support
mindstorm38/portablemc pull request #240
Opened 2024-12-25 13:55 UTC by pi-dev500

This file add a complete optifine support, but you should improve it for events support. Please notify me if you get any errors. And happy christmas for everyone  !

2024-12-25 14:26 UTC, mindstorm38 commented
Wow 😳 Insane work, yes there is some huge refactor to do for the events system but all this patch reimplementation is insane, great work!

2024-12-31 21:06 UTC, pi-dev500 commented
Worked a bit on that today, but it's a bit hard to figure in which order to install the thing... looking in the code of forgeversion helped me.

2025-01-01 18:02 UTC, mindstorm38 commented
Side note, with the upcoming Rust rewrite, would you be interested in adapting this code directly into it ? I think the first releases will not includes optifine support, if you don't want to do it I'll do it but you'll definitely be credited for that module.

2025-01-02 11:28 UTC, pi-dev500 commented
As I never written anything in Rust, I'll need some adaptation time, but first, I prefer do the whole algorithm in python, an then copy the code to another language. In fact, my event handling is not far from being ready, but I think that marking this python PR as draft is needed, as it is still in progress, and will probably not be merged.

2025-01-02 14:42 UTC, pi-dev500 commented
The only python deps were beautifulsoup4 and requests, requests is on the way to be deleted, and beautifulsoup4 is only used to list available versions, so realy no problem on that side, removing them will be easy.

2025-01-02 20:57 UTC, mindstorm38 commented
Thank you for putting so much attention into this

2025-01-04 17:32 UTC, pi-dev500 commented
The event system is there, and the install process is much cleaner and understandable. On top of that, I removed the two dependencies (requests and beautifulsoup4). Next to do for me: handling the new api in the CLI launcher... Search method should be simple to integrate (have a look at optifine.get_compatible_versions). Loader version are currently names like this: "preview_OptiFine_1.21.4_HD_U_J3_pre6" I should shorten them to things like "HD_U_J3_pre6"

2025-01-05 18:37 UTC, mindstorm38 commented
Perfect! Do you want a pre-review on the API code, I don't want to spam you with change requests if the code is not yet 90% ready. 
Yes, you should try to shorten the loader version, without making it ambigous! This looks good like this.

2025-01-10 14:59 UTC, mindstorm38 commented
Just for information, the forge version specifier will be modified with the upcoming Rust rewrite. Here's the help message:
```
- forge::<loader-version> | forge:[<game-version>][:stable|unstable] => the 
syntax is a bit cumbersome because you can either specify the full loader version
such as '1.21.4-54.0.12' but you must leave the first parameter empty, or you 
can specify a Mojang game version with optional second parameter that specifies
if you target the latest 'stable' (default) or 'unstable' loader version.
See https://minecraftforge.net/.
```

Anyway, for OptiFine, I would like to use another format, like `optifine:[<game-version>[:<edition>]]`. For example `optifine:` will start the latest optifine version for the latest release, `optifine:1.21.3` at the time of writing would be equivalent to `optifine:1.21.3:HD_U_J2`. We can automatically handle the `preview_` prefix if we find a `_preX` suffix in the edition string.

Tell we what do you think.

2025-01-11 08:17 UTC, pi-dev500 commented
I mean, the directory name used to store the version in the version directory. To start Optifine, I already support this format, but also several others thanks to regex (I saw that regex are well-supported by rust). I currently have both, the name used by sp614x, and the prefix system that is used in ForgeVersion and FabricVersion. I don't really know which one I have to keep.

2025-02-07 12:24 UTC, mindstorm38 commented
Hello, I'm working on version 4.5 and I would like to include your work, together with another small fix. Is your PR ready ? If there is more work, I can handle it, but can you rebase your work on the version-4.5 branch before?

2025-02-08 13:51 UTC, pi-dev500 commented
The only work is to finalise the help in the API (included some keys and params for that in lang), remove debug prints in _resolve_version and there seems to have no conflicts with your current changes in 4.5, so this should be quite easy.

2025-02-08 16:48 UTC, mindstorm38 requested changes
First batch of code review, really promising!

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> -
Formatting, don't remove this space.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> -
Keep space

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> -
Keep space

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> +            optifine.OptifinePatchEvent: lambda e: progress_task("start.optifine.patching", progress=f"{e.done}/{e.total}"),
Really good! You can omit the `optifine.` prefix if you directly import the events, as commented on the top of the file.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/lang.py
> +    "search.OptiFine.ForgeCompatibility": "Forge compatibility",
Please use lowercase `snake_case` for this key, like `seach.optifine.forge_compatibility`, remember to change it where it's used.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> +            ns.work_dir=c.work_dir
Just use `ns.context.work_dir`, you should not create a `Context` here.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/download.py
> +            url_parsed.path+("" if url_parsed.query == "" else "?"+url_parsed.query),
Good!

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        if re.match(r"pre\d",edition.split("_")[-1]):
General formatting: space after comma `,`.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +    def __init__(self, filename: str, edition: str, mc_version: str, preview: bool =False, date: Optional[str] | None =None, forge: Optional[str] | None =None):
Type annotation `Optional[T] | None` is redundant, just use `Optional[T]`, the `| None` syntax is only supported since Python 3.10 and we want to support down to 3.8

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        filename+="OptiFine_"+mcver+"_"+edition
Prefer using format strings instead of `+`: `f"OptiFine_{mcver}_{edition}"`.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        edition=n[1]
I'm afraid of this pattern, what happen if the split don't give an array with two elements? Or more? I think it would be better to check for the split size, or handle any error related to it. You can also use list destructuring, using `mcver, edition = name.split("...")`

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +    @classmethod
General formatting: on empty line before every method

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +    __slots__ = tuple(["version"])
You can write `__slots__ = "version",`

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        if not (self.context.versions_dir / self.version / "ofInstaller.jar").exists():
For computing the path of the installer, please prefer `self._hierarchy[0].dir / "ofInstaller.jar"` instead of recomputing the version, it should work properly, replace this everywhere when relevant.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        if not (self.context.versions_dir / self.version / "ofInstaller.jar").exists():
Also, you use this "ofInstaller.jar" thing many times, you could define a constant like `INSTALLER_FILE_NAME = "of-installer.jar` (I prefer the kebab-case)

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +                    launchwrapper_version=jar.open("launchwrapper-of.txt").read().decode("utf-8").strip()
`launchwrapper-of.txt` is opened twice, prefer opening it once before those lines and then use its result.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +                    dir_dest = self.context.libraries_dir / f"optifine/launchwrapper-of/{launchwrapper_version}"
Use the separator pattern: `self.context.libraries_dir / "optifine" / "launchwrapper-of" / launchwrapper_version`

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        version = VersionHandle(self.version, self.context.versions_dir / self.version)
Don't need to re-construct a version handle, simply use the hierarchy `self._hierarchy[0]` contains the top-level version handle.

2025-02-08 16:48 UTC, mindstorm38 commented on portablemc/optifine.py
> +        version.write_metadata_file()
I think that, like `ForgeVersion`, you could put all the downloading/patching/metadata writing stuff in this function, instead of the `_resolve_jar` function, if you need to finalize the JAR file then you can, just like `ForgeVersion`, call the finalizer in it:
![image](https://github.com/user-attachments/assets/26e5b2da-8f1c-4f2a-88e8-304a9a72ba1d)

2025-02-08 19:57 UTC, pi-dev500 commented on portablemc/optifine_withprefix.py
yeah, that was for you to choose between the two version name format in version directory: Official one used by sp14x and the other which is basically the same as in ForgeVersion

2025-02-08 19:58 UTC, pi-dev500 commented on portablemc/cli/__init__.py
> +
Yes, this was for testing purpose- > no need to keep it

2025-02-08 19:59 UTC, pi-dev500 commented on portablemc/cli/__init__.py
> +                    table.add(f"{loader.mc_version}-OptiFine_{loader.edition}", loader.date, _("search.flags.stable") if not loader.preview else "preview", loader.forge if loader.forge else "")
In fact, yes, I forgot about reformatting my code to be PEP-compliant ! Sorry :)

2025-02-08 20:16 UTC, pi-dev500 commented on portablemc/optifine.py
> +        version.write_metadata_file()
I just wanted to have the Optifine download progress in the global progress, and in fact we can only generate json and install libs if we don't have version jar. But I can change it.

2025-02-08 20:17 UTC, mindstorm38 commented on portablemc/optifine_withprefix.py
Ohh ok I understand!

2025-02-08 20:17 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> +                    table.add(f"{loader.mc_version}-OptiFine_{loader.edition}", loader.date, _("search.flags.stable") if not loader.preview else "preview", loader.forge if loader.forge else "")
No problem!

2025-02-09 11:28 UTC, mindstorm38 commented on portablemc/optifine.py
> +        version.write_metadata_file()
Yes this make sense also! This is more for coherency with forge, but also because I find it weird to write a "mock" version metadata when it is missing, that will be later modified in the resolve jar function. 

Anyway, all of this has been badly designed and this is why I reworked all of this in Rust.

2025-02-11 11:44 UTC, pi-dev500 commented on portablemc/optifine.py
> +        edition=n[1]
In fact, if the regex is matched, there should be no issue. I'll just switch to destructuring.

2025-02-11 14:39 UTC, pi-dev500 commented on portablemc/optifine_withprefix.py
Which one do you prefer ?

2025-02-15 14:11 UTC, mindstorm38 commented on portablemc/optifine_withprefix.py
I prefer just prefixing the full Optifine version with a prefix like `optifine-` while removing the "OptiFine_" prefix of the version.

2025-02-15 16:25 UTC, pi-dev500 commented on portablemc/optifine_withprefix.py
Just did it: default format is now `optifine-{mc_version}-{optifine_edition}`

latest recommended is for exemple: optifine-1.21.4-HD_U_J3

2025-02-15 17:17 UTC, mindstorm38 commented on portablemc/optifine_withprefix.py
Perfect!

2025-02-21 13:54 UTC, mindstorm38 commented on portablemc/cli/lang.py
> +    "args.start.version.comp.optifine": "Start Optifine mod loader with latest recommended release.",
To actually use this, yiou should add `"optifine"` to the tuple in `parse.py`: `for loader in ("fabric", "quilt", "legacyfabric", "babric", "forge", "neoforge"):`.

2025-02-21 13:54 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> +        return constructor(":".join(parts) if len(parts) > 0 else "recommended", context = ns.context)
Don't really need to use `constructor`, just use the class name directly.

2025-02-21 13:54 UTC, mindstorm38 commented on portablemc/cli/__init__.py
> +                                get_compatible_versions as optifine_get_versions,
Why renaming the two differently, like `get_offline_versions` is reverted `get_versions_offline` in the alias? And for the compatible versions, why is the word "compatible" gone? I know I'm annoying sorry I'm a maniac lol

2025-02-21 13:54 UTC, mindstorm38 commented on portablemc/optifine.py
> +class Patcher:
If this class is internal, please prefix it with an underscore, and in general please do that for everything that is internal! We want to be very precise about what is publicly exposed, to ensure backward compatibility.

2025-02-28 19:45 UTC, mindstorm38 commented on test.py
I guess that it's just for your personal test, no worry but remove it before final version!

2025-03-01 07:24 UTC, pi-dev500 commented on test.py
Github desktop always wanted to push this file on the repo, and it finished by doing it 😅. I just deleted the file.

2025-03-01 18:06 UTC, mindstorm38 commented on test.py
No problem indeed! :)

2025-03-01 18:08 UTC, mindstorm38 commented
I'll be doing a last review and merge it soon if everything is ok. I may do some changes to it afterward but globally this is the most impressive contribution so far so thank you!

2025-03-24 13:43 UTC, merged

2025-03-24 13:44 UTC, mindstorm38 commented
Now working on fixing some issues with testing.